const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.video.Cnds.IsPaused,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Pause
	];
};
self.C3_JsPropNameTable = [
	{button_course: 0},
	{button_instruction: 0},
	{button_review: 0},
	{button_test: 0},
	{button_book: 0},
	{button_home: 0},
	{button_last: 0},
	{button_next: 0},
	{button_que: 0},
	{button_test1: 0},
	{button_test2: 0},
	{button_test3: 0},
	{button_close: 0},
	{button_sound: 0},
	{button_nextQ: 0},
	{Sprite: 0},
	{button_word1: 0},
	{button_word2: 0},
	{button_word3: 0},
	{button_word4: 0},
	{top_close: 0},
	{subtitle: 0},
	{進入循環系統功能: 0},
	{進入肺循環: 0},
	{進入體循環: 0},
	{background: 0},
	{Instructions: 0},
	{train: 0},
	{num1: 0},
	{num2: 0},
	{num3: 0},
	{num4: 0},
	{num5: 0},
	{拖放: 0},
	{動脈: 0},
	{右心房: 0},
	{左心室: 0},
	{微血管: 0},
	{框1: 0},
	{框2: 0},
	{框3: 0},
	{框4: 0},
	{框5: 0},
	{靜脈: 0},
	{閃爍: 0},
	{choose1: 0},
	{choose2: 0},
	{choose3: 0},
	{choose4: 0},
	{choose5: 0},
	{S1: 0},
	{S2: 0},
	{S3: 0},
	{S4: 0},
	{S5: 0},
	{top: 0},
	{review_text: 0},
	{Touch: 0},
	{white: 0},
	{視頻: 0},
	{touch_pause: 0},
	{letsgo: 0},
	{音頻: 0},
	{sentence_blank: 0},
	{word_know: 0},
	{體循環icon: 0},
	{肺循環icon: 0},
	{p: 0},
	{p13: 0},
	{p13整章: 0},
	{視頻2: 0},
	{進入比較: 0},
	{體循環按鈕: 0},
	{肺循環按鈕: 0},
	{match: 0},
	{chooses: 0},
	{ss: 0},
	{pause: 0},
	{video_play: 0},
	{test_num: 0},
	{choose_num: 0},
	{sentence_num: 0},
	{test_01: 0},
	{test_02: 0},
	{test_03: 0}
];

self.InstanceType = {
	button_course: class extends self.ISpriteInstance {},
	button_instruction: class extends self.ISpriteInstance {},
	button_review: class extends self.ISpriteInstance {},
	button_test: class extends self.ISpriteInstance {},
	button_book: class extends self.ISpriteInstance {},
	button_home: class extends self.ISpriteInstance {},
	button_last: class extends self.ISpriteInstance {},
	button_next: class extends self.ISpriteInstance {},
	button_que: class extends self.ISpriteInstance {},
	button_test1: class extends self.ISpriteInstance {},
	button_test2: class extends self.ISpriteInstance {},
	button_test3: class extends self.ISpriteInstance {},
	button_close: class extends self.ISpriteInstance {},
	button_sound: class extends self.ISpriteInstance {},
	button_nextQ: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	button_word1: class extends self.ISpriteInstance {},
	button_word2: class extends self.ISpriteInstance {},
	button_word3: class extends self.ISpriteInstance {},
	button_word4: class extends self.ISpriteInstance {},
	top_close: class extends self.ISpriteInstance {},
	subtitle: class extends self.ISpriteInstance {},
	進入循環系統功能: class extends self.ISpriteInstance {},
	進入肺循環: class extends self.ISpriteInstance {},
	進入體循環: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Instructions: class extends self.ISpriteInstance {},
	train: class extends self.ISpriteInstance {},
	num1: class extends self.ISpriteInstance {},
	num2: class extends self.ISpriteInstance {},
	num3: class extends self.ISpriteInstance {},
	num4: class extends self.ISpriteInstance {},
	num5: class extends self.ISpriteInstance {},
	動脈: class extends self.ISpriteInstance {},
	右心房: class extends self.ISpriteInstance {},
	左心室: class extends self.ISpriteInstance {},
	微血管: class extends self.ISpriteInstance {},
	框1: class extends self.ISpriteInstance {},
	框2: class extends self.ISpriteInstance {},
	框3: class extends self.ISpriteInstance {},
	框4: class extends self.ISpriteInstance {},
	框5: class extends self.ISpriteInstance {},
	靜脈: class extends self.ISpriteInstance {},
	choose1: class extends self.ISpriteInstance {},
	choose2: class extends self.ISpriteInstance {},
	choose3: class extends self.ISpriteInstance {},
	choose4: class extends self.ISpriteInstance {},
	choose5: class extends self.ISpriteInstance {},
	S1: class extends self.ISpriteInstance {},
	S2: class extends self.ISpriteInstance {},
	S3: class extends self.ISpriteInstance {},
	S4: class extends self.ISpriteInstance {},
	S5: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	review_text: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	white: class extends self.ISpriteInstance {},
	視頻: class extends self.IWorldInstance {},
	touch_pause: class extends self.ISpriteInstance {},
	letsgo: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	sentence_blank: class extends self.ISpriteInstance {},
	word_know: class extends self.ISpriteInstance {},
	體循環icon: class extends self.ISpriteInstance {},
	肺循環icon: class extends self.ISpriteInstance {},
	p: class extends self.ISpriteInstance {},
	p13: class extends self.ISpriteInstance {},
	p13整章: class extends self.ISpriteInstance {},
	視頻2: class extends self.IWorldInstance {},
	進入比較: class extends self.ISpriteInstance {},
	體循環按鈕: class extends self.ISpriteInstance {},
	肺循環按鈕: class extends self.ISpriteInstance {},
	match: class extends self.ISpriteInstance {},
	chooses: class extends self.ISpriteInstance {},
	ss: class extends self.ISpriteInstance {}
}